.TH NOSPC 1 "June 2024" "nospc 1.0" "User Commands"
.SH NAME
nospc \- detect and highlight non-ASCII whitespace characters

.SH SYNOPSIS
.B nospc
[\fI-c|--color\fR] [\fI-b|--bracket\fR] [\fI-r|--recursive\fR] \fIfilename\fR...

.SH DESCRIPTION
.B nospc
is a utility to detect and highlight non-ASCII whitespace characters in text files. It supports highlighting using either colored text or enclosing characters in brackets.

.SH OPTIONS
.TP
.B \-c, \--color
Enable color highlighting.
.TP
.B \-b, \--bracket
Enable bracket highlighting with Unicode information.
.TP
.B \-r, \--recursive
Recursively process directories.

.SH ARGUMENTS
.TP
\fIfilename\fR
One or more input filenames. Use "-" to read from standard input.

.SH EXAMPLES
.TP
Detect and highlight non-ASCII whitespace characters in a file using colored text:
.RS
.nf
.B nospc -c file.txt
.RE
.fi
.TP
Detect and highlight non-ASCII whitespace characters in a file using brackets:
.RS
.nf
.B nospc -b file.txt
.RE
.fi
.TP
Read from standard input and highlight using colored text:
.RS
.nf
.B cat file.txt | nospc -c -
.RE
.fi
.TP
Read from standard input and highlight using brackets:
.RS
.nf
.B cat file.txt | nospc -b -
.RE
.fi


